config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Pages routes
  root to: 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'web', to: 'pages#web'
  get 'woodwork', to: 'pages#woodwork'

  resources :projects

  match '*_missing_page', to: 'pages#not_found', via: :get


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  has_many_attached :photos
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :projects

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :contact, :web, :woodwork]

  def home
    @projects = Project.all
  end

  def contact
  end

  def web
    @projects = Project.all
  end

  def woodwork
    @projects = Project.all
  end

  def not_found
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @projects = policy_scope(Project)
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project

    if @project.save
      redirect_to root_path(@project), notice: "Le nouveau projet a bien été créé"
    else
      render :new
    end
  end

  def edit
    set_project
  end

  def update
    set_project

    @project.update(project_params)
    redirect_to project_path(@project), notice: "Le projet a bien été mis à jour"
  end

  def destroy
    set_project
    @project.destroy
    redirect_to root_path(@project), notice: "Le projet a bien été supprimé"
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :is_woodworking, :is_web, photos: [] )
  end

  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <%= yield %>

    <%= render 'shared/footer' %>
    
    <%= render "shared/flashes" %>

  </body>
</html>

app/views/pages/contact.html.erb
<div class="container d-flex flex-direction-row align-items-center">
    <div class="profile--picture">
      <%= cl_image_tag("https://res.cloudinary.com/dus151ezt/image/upload/v1677551514/Portfolio/Stuck_at_Home_-_Sitting_On_Floor_tlaxr2.png", crop: :fill, class: "rounded") %>
    </div>
  <div class="introduction">
    <h3>
      Hey I’m Cyrille,
    </h3> 
    <p>
      a fullstack web developer. This is my tech portfolio and here you’ll find my code projects but also some of my side projects as a woodworker.</p>
    <h3>
      About me
    </h3>
    <p>
      After long studies (and a short career) in geopolitical analysis in France, Poland and Canada, I’ve been working in Finance for the last 5 years.
      <br>In 2020 I completed a full stack web development bootcamp in Montreal, then started freelancing.
    </p>
    <h3>
      Technologies
    </h3> 
    <p>
      I’m building apps using Ruby on Rails, HTML, CSS SQL, and MVC models, web pages behaviour programming using JavaScript, jQuery, AJAX and Bootstrap.
    </p>
  </div>

</div>

app/views/pages/home.html.erb
<div class="home container">
    <div class="home--picture d-flex justify-content-center">
      <%= cl_image_tag("https://res.cloudinary.com/dus151ezt/image/upload/v1676524112/Group_13_vrjjmp.svg", crop: :fill) %>
    </div>
    <%= link_to "Launch your website!", web_path %>
</div>

app/views/pages/not_found.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center">
  <h1>Oops!</h1>
  <h2>404 - Page not found</h2>
  <p>The page you are looking for might have been removed, <br>had its name changed or is temporarily unavailable.</p>
  <%= link_to "Go to homepage", root_path, class: "btn btn-danger" %>
</div>

app/views/pages/web.html.erb
<div class="container d-flex justify-content-center align-items-center">
  <div class="web">
    <h4 class="d-flex justify-content-center">Section under construction</h4>
    <iframe src="https://giphy.com/embed/fVeAI9dyD5ssIFyOyM" width="600" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/OctoNation-work-construction-fVeAI9dyD5ssIFyOyM"></a></p></div>
</div>

app/views/pages/woodwork.html.erb
<div class="container">
  <div class="row">

    <% @projects.each do |project| %>
      <% if project.is_woodworking == true %>
        <div class="col-6">

          <div class="card m-3" style="width: 30vw;">

            <div class="card-img-top">
              <% project.photos.each do |photo| %>
                <% if project.photos[0] %>
                  <%= cl_image_tag photo.key, crop: :fill %>
                  <% break %> 
                <% end %>
              <% end %>
            </div>

            <div class="card-body">
              <h3 class="card-title d-flex justify-content-center"><%= link_to project.name, project_path(project) %></h3>
            </div>

          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>

app/views/projects/edit.html.erb
<h3 class="form-group">Veuillez modifier votre projet item</h3>

<%= form_with model: @project, method: :patch do |f| %>

  <div class="form-group">
    <%= f.label :name, "Modifiez le nom" %>
    <%= f.text_field :name, class:"form-control", placeholder: "Champ obligatoire" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Modifiez la description" %>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <p>Sur quel page souhaitez-vous ajouter votre nouvel item ?</p>
  <div>
    <%= f.check_box :is_woodworking %>
    <%= f.label :is_woodworking, "Woodworking" %>
  </div>
  <div>
    <%= f.check_box :is_web %>
    <%= f.label :is_web, "Web development" %>
  </div>
  <div class="form-group">
    <%= f.label :photos, "Sélectionnez vos images" %>
    <%= f.file_field :photos, multiple: true, class:"form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.submit class:"btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

<div>
  <%= link_to 'Back to the main page', root_path %></p>
</div>

app/views/projects/new.html.erb
<% if policy(@project).create? %>

  <div class="container new-form d-flex justify-content-around">

    <div class="form-group text-start border border-light rounded p-4">

      <h4 class="form-group text-start">Veuillez entrer les détails de votre projet</h4>

      <%= form_with model: @project, method: :post do |f| %>

        <div class="mb-3">
          <%= f.text_field :name, class:"form-control", placeholder:"Indiquez le nom" %>
        </div>

        <div class="mb-3">
          <%= f.text_area :description, class:"form-control", placeholder: "Ajoutez une description" %>
        </div>

        <div class="d-flex align-items-center justify-content-between">
          <div class="mb-3">
            <div>Il s'agit d'un projet en :</div>
            <div>
              <%= f.check_box :is_woodworking %>
              <%= f.label :is_woodworking, "Menuiserie" %>
            </div>
            <div>
              <%= f.check_box :is_web %>
              <%= f.label :is_web, "Web" %>
            </div>
          </div>

          <div class="mb-3">
            <div><%= f.label :photos, "Sélectionnez vos images :", class: "form-label" %></div>
            <div><%= f.file_field :photos,  multiple: true, class:"form-control-file" %></div>
          </div>
        </div>

        <div class="mb-3 d-flex justify-content-center">
          <%= f.submit class:"btn btn-primary btn-lg btn-block" %>
        </div>

      <% end %>

      <div class="no-style d-flex align-items-end">
        <%= link_to "Retour à l'accueil", root_path %>
      </div>

    </div>

    <div class="picture text-center">
      <%= cl_image_tag("https://res.cloudinary.com/dus151ezt/image/upload/v1614447271/roadcypressesv_ivna6i.jpg", crop: :fill, class:"rounded") %>
    </div>

  </div>

<% end %>

app/views/projects/show.html.erb
<div class="container d-flex flex-row">

    <div>
      <% @project.photos.each_with_index do |photo| %>
        <div><%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %></div>
      <% end %>
    </div>

  <div class="d-flex flex-column align-items-center justify-content-between border border-light rounded p-4">
    <div>
      <h1><%= @project.name %></h1>
      <p><%= @project.description %></p>
    </div>

      <div class="d-flex flex-row justify-content-around">
        <% if policy(@project).edit? %>
          <div>
            <%= link_to "Mettre à jour", edit_project_path(@project), class: "btn btn-warning" %>
          </div>
        <% end%>
        <% if policy(@project).destroy? %>
          <div>
            <%= link_to "Supprimer",
              project_path(@project),
              data: {turbo_method: :delete, turbo_confirm: "Sûr de ton coup ?"},
              class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>

    <div>
      <% if @project.is_web == true %>
        <%= link_to "Retour", web_path, class: "btn btn-danger" %>
      <% else @project.is_woodworking == true %>
          <%= link_to "Retour", woodwork_path, class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex flex-direction-row align-items-center justify-content-between">

  <div class="footer-links d-flex flex-direction-row align-items-center">
    <a href="https://github.com/cgawlowski" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://twitter.com/ici_myrtille" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://linkedin.com/in/cyrille-gawlowski-42436643" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>

  <div class="footer-email d-flex align-items-center justify-content-around">
    <div class="d-flex align-items-center"><i class="fa-solid fa-envelope"></i></div>
    <div class="d-flex align-items-center"><a href="gawlowski.cyrille@gmail.com">gawlowski.cyrille@gmail.com</a></div>
  </div>

  <div class="footer-copyright d-flex flex-direction-row align-items-center justify-content-around">
    <div><i class="fa-sharp fa-solid fa-copyright"></i></div>
    <div>2023</div> 
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="topnav sticky d-flex justify-content-between align-items-center">

  <div class="logo d-flex align-self-center">
    <div>
      <%= cl_image_tag(
        "https://res.cloudinary.com/dus151ezt/image/upload/v1675912302/Avatar_vwmnxn.png",
        crop: :fill) %>
    </div>
    <div class="logo--text">
      <p>Cyrille</p>
      <p>web developer</p>
    </div>
  </div>
  <div class="text-align-right topBotomBordersIn ">
    <%= link_to "Home", root_path %>
    <%= link_to "Web", web_path %>
    <%= link_to "Woodwork", woodwork_path %>
    <%= link_to "Contact", contact_path %>
    <% if current_user && current_user.admin? %>
      <%= link_to "New", new_project_path %>
    <% end %>
  </div>

</div>